### ISSUE TITLE
Is the project maintained?

### ISSUE THREAD

**Issue by mcorossigo** [dataproofer/Dataproofer#160]
Hello @enjalot , @newsroomdev 
Thanks for this nice, interesting product
this is the "obligatory" issue to check/track any kind of future plan or vision you guys have for this project.

As it sometimes happens, the repo is collecting dust, with the electron version required being incredibly old (and insecure) and many other proplems..

So any information is welcome.
Thank you!

**Comment by ejfox** [comment]
Hey @mcorossigo - you are absolutely correct, things are a bit dusty around here.

To answer your question: "Is the project maintained" - I think that answer, unfortunately, is obviously not.''

However the answer to a different question "Do we want to do a better job of maintaining it?" the answer is a strong yes. 

For me personally, I am split between wanting to develop the more user-friendly Electron app or, instead, working on a more robust commandline version that could easily be integrated into workflows where people are already piping data between things like [jq](https://github.com/stedolan/jq) or [csvkit](https://csvkit.readthedocs.io/en/latest/)

I think if someone (like yourself) wanted to take up the mantle of organizing a set of issues into a new version, or otherwise plotting a way forward that seems appealing to you, I think that you could create some new energy around making those things happen.
