### ISSUE TITLE
Table comments disappear after filtering

### ISSUE THREAD

**Issue by geraldarthur** [dataproofer/Dataproofer#77]
### Summary
When selecting a filtered view to see only the column with errors for a certain tests, all the comments disappear.
### Steps to reproduce
Load any spreadsheet, then click on the test to highlight the minimap and filter the grid 
### Expected behavior
All of the comments on the cells disappeared. Unable to see other cells with possibly related errors
### Relevant logs and/or screenshots
![filtered-cell-comments](https://cloud.githubusercontent.com/assets/1578563/14335362/67aa4aba-fc0f-11e5-9fec-21e02e97c073.gif)
### Possible fixes?
`renderCellComments` is not setup to handle filtered rows. logic needs to be reworked to attach comments to cells independent of their original row indices.

**Comment by ejfox** [comment]
I think once we highlight the check title, it will make more sense. You don't really need them to be labeled since you're looking at one check filter at a time. You just need to be reminded of what you're looking at by bolding the title on the left. 

Think we can close this once https://github.com/dataproofer/Dataproofer/issues/78 is closed

**Comment by ejfox** [comment]
imo, it makes sense to not have the comments when you are in filter view

you're looking specifically at one error, I don't think you need to double-encode the error

gonna close unless you have objections @geraldarthur
