### ISSUE TITLE
Show large file warning based on JSON byte size

### ISSUE THREAD

**Issue by ejfox** [dataproofer/Dataproofer#90]
Currently we just limit to the first 1000 rows

Jason suggested (and I agree) that instead we simply issue a warning about large files and the fact they might take a long time (or break the app)

**Comment by geraldarthur** [comment]
Taking a first draft at the copy here before popping it in.

> Warning: Depending upon your computer's capabilities, this app may crash while proofing large datasets. Please `npm install` any **test set** (link to npm page) or help us reach version 2 (link to roadmap).

**Comment by ejfox** [comment]
> LARGE FILE ALERT: Dataproofer relies on your computer's processing power. The higher the spec of your machine, the lower the risk the app may crash when processing large datasets. If your dataset is extremely large, we suggest loading samples of 1000 rows.

Signed off by Markham

**Comment by geraldarthur** [comment]
We need a way to detect the number of number of bytes in a JSON object in order to render the notification for users with larger datasets. Files have file sizes, but Google Spreadsheets do not. This requires further investigation.

**Comment by enjalot** [comment]
I think we can catch 90% of the cases by estimating using # of rows times # of columns. the `65k.csv` file is actually larger than the `large_tweet_dataset.csv` in terms of bytes, but has far fewer rows (it has long strings). the `65k.csv` actually renders pretty decently. I think its because performance is limited more by the for loops we do over all the rows and columns rather than the memory used. So the more cells we have to process the more of a performance hit we will take.
